version: '3.8'

services:
  # Frontend (React) service
  frontend:
    build:
      context: ./frontend
    container_name: mern-frontend
    restart: always
    ports:
      - "80:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3500/api/tasks #http://backend:3500/api/tasks
    depends_on:
      - backend
    networks:
      - mern-net

  # Backend (Node.js/Express) service
  backend:
    build:
      context: ./backend
    container_name: mern-backend
    restart: always
    ports:
      - "3500:3500"
    environment:
      - MONGO_CONN_STR=mongodb://mongo:27017/admin
      - USE_DB_AUTH=false
    depends_on:
      - mongo
    networks:
      - mern-net

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mern-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-net

volumes:
  mongo-data:

networks:
  mern-net:
